# TODO: split out production and dev config (this is dev config for now)
name: chat-7b

services:
  server:
    image: chat-7b-backend-image
    container_name: chat-7b-backend
    build:
      context: .
    volumes:
      - ${USERPROFILE}/.cache/huggingface/hub:/models
    environment:
      - LOCAL_MODEL_PATH=/models/models--HuggingFaceH4--zephyr-7b-beta/snapshots/892b3d7a7b1cf10c7a701c60881cd93df615734c
      - UVICORN_RELOAD=true
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
